global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['springboot:8080','service1:8081']

#  - job_name: 'fastapi'
#    metrics_path: '/metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['fastapi:8000']
